// Command catalog-review compares live account availability with current public provider evidence
// and writes proposal-only artifacts. It never writes the active operator YAML or SQLite state.
package main

import (
	"context"
	"flag"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/lynn/porcelain/chimera/internal/cataloglimits"
	"github.com/lynn/porcelain/chimera/internal/catalogreview"
	"github.com/lynn/porcelain/chimera/internal/freecatalog"
	"github.com/lynn/porcelain/chimera/internal/providerfreetier"
	"github.com/lynn/porcelain/chimera/internal/providerlimits"
	"gopkg.in/yaml.v3"
)

const (
	defaultGroqURL   = "https://console.groq.com/docs/rate-limits"
	defaultGeminiURL = "https://ai.google.dev/gemini-api/docs/pricing"
)

func main() {
	catalogPath := flag.String("catalog", "config/catalog-available.snapshot.yaml", "live BiFrost catalog YAML generated by catalog-write-available")
	activeFreeTier := flag.String("active-free-tier", "config/provider-free-tier.yaml", "active operator free-tier allowlist (read-only)")
	activeLimits := flag.String("active-limits", "config/provider-model-limits.yaml", "active operator provider limits (read-only)")
	operatorSQLite := flag.String("operator-sqlite", "data/gateway/operator.sqlite", "operator SQLite path (read-only; optional)")
	freeSnapshotOut := flag.String("free-snapshot-out", "config/catalog-free-tier.snapshot.yaml", "public evidence snapshot output")
	freeTierOut := flag.String("provider-free-tier-out", "config/provider-free-tier.generated.yaml", "proposal-only free-tier YAML output")
	limitsOut := flag.String("provider-limits-out", "config/provider-model-limits.generated.yaml", "proposal-only limits YAML output")
	reportOut := flag.String("report-out", "config/catalog-review.proposal.yaml", "semantic review report output")
	codingOut := flag.String("coding-model-out", "config/coding-virtual-model.proposal.yaml", "future coding virtual-model proposal output")
	groqURL := flag.String("groq-url", defaultGroqURL, "official Groq rate-limits page")
	geminiURL := flag.String("gemini-url", defaultGeminiURL, "official Gemini pricing page")
	timeout := flag.Duration("timeout", 60*time.Second, "per-provider fetch timeout")
	flag.Parse()

	protectedInputs := []string{*catalogPath, *activeFreeTier, *activeLimits}
	if strings.TrimSpace(*operatorSQLite) != "" {
		protectedInputs = append(protectedInputs, *operatorSQLite)
	}
	if err := rejectOutputCollisions(protectedInputs, []string{*freeSnapshotOut, *freeTierOut, *limitsOut, *reportOut, *codingOut}); err != nil {
		fatal(err)
	}
	now := time.Now().UTC()
	live, err := catalogreview.LoadCatalog(*catalogPath)
	if err != nil {
		fatal(err)
	}
	activeFree, err := providerfreetier.Load(*activeFreeTier)
	if err != nil {
		fatal(fmt.Errorf("load active free tier: %w", err))
	}
	limits, err := providerlimits.Load(*activeLimits)
	if err != nil {
		fatal(fmt.Errorf("load active limits: %w", err))
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout*3)
	defer cancel()
	public, err := freecatalog.FetchPublicEntries(ctx, &http.Client{Timeout: *timeout}, *groqURL, *geminiURL)
	if err != nil {
		fatal(err)
	}
	if err := ensureParent(*freeSnapshotOut); err != nil {
		fatal(err)
	}
	if _, err := freecatalog.WriteCatalogYAML(*freeSnapshotOut, now, *groqURL, *geminiURL, public); err != nil {
		fatal(err)
	}

	liveIDs := make([]string, 0, len(live))
	for _, model := range live {
		liveIDs = append(liveIDs, model.ID)
	}
	livePublic := freecatalog.AlignEntriesToCatalog(freecatalog.FilterEntriesByCatalog(public, liveIDs), liveIDs)
	if err := ensureParent(*freeTierOut); err != nil {
		fatal(err)
	}
	if err := freecatalog.WriteProviderFreeTierYAML(*freeTierOut, now, livePublic, activeFree.Patterns); err != nil {
		fatal(err)
	}

	contextMap, err := cataloglimits.LoadCatalogContextLengths(*catalogPath)
	if err != nil {
		fatal(err)
	}
	catalogIDs, err := cataloglimits.CatalogModelIDs(*catalogPath)
	if err != nil {
		fatal(err)
	}
	contextReport := cataloglimits.ApplyContextWindows(limits, contextMap, catalogIDs, cataloglimits.ApplyOptions{})
	quotaChanges := catalogreview.ApplyPublishedGroqLimits(limits, public)
	if err := ensureParent(*limitsOut); err != nil {
		fatal(err)
	}
	if err := cataloglimits.WriteLimitsFile(*limitsOut, limits); err != nil {
		fatal(err)
	}

	chains, operatorState, err := catalogreview.LoadOperatorChains(*operatorSQLite)
	if err != nil {
		fatal(fmt.Errorf("read operator SQLite: %w", err))
	}
	contextChanges := contextChangeLines(contextReport, catalogIDs)
	report := catalogreview.BuildReport(now, catalogSource(*catalogPath), *groqURL, *geminiURL, operatorState, live, public, activeFree, contextChanges, quotaChanges, chains)
	reportYAML, err := catalogreview.MarshalYAML(report)
	if err != nil {
		fatal(err)
	}
	if err := writeProposal(*reportOut, reportYAML); err != nil {
		fatal(err)
	}

	coding := catalogreview.BuildCodingProposal(now, live, limits, public)
	codingYAML, err := catalogreview.MarshalYAML(coding)
	if err != nil {
		fatal(err)
	}
	if err := writeProposal(*codingOut, codingYAML); err != nil {
		fatal(err)
	}

	fmt.Fprintf(os.Stderr, "catalog-review: live=%d public_free=%d general_candidates=%d specialist_excluded=%d retired_or_removed=%d\n",
		report.Summary.LiveModels, report.Summary.PublicFreeModels, report.Summary.GeneralCandidates,
		len(report.Summary.SpecialistsExcluded), len(report.Summary.RetiredOrRemoved))
	fmt.Fprintf(os.Stderr, "catalog-review: proposals: %s, %s, %s, %s\n", *freeTierOut, *limitsOut, *reportOut, *codingOut)
	if len(coding.EffectiveFallbackChain) > 0 {
		fmt.Fprintf(os.Stderr, "catalog-review: coding chain proposal: %s\n", strings.Join(coding.EffectiveFallbackChain, " -> "))
	} else {
		fmt.Fprintln(os.Stderr, "catalog-review: coding chain proposal is empty (no available capable model with known context)")
	}
}

func contextChangeLines(report cataloglimits.ApplyReport, liveCatalogIDs []string) []string {
	var out []string
	for _, value := range report.Added {
		out = append(out, "added "+value)
	}
	for _, value := range report.Updated {
		out = append(out, "updated "+value)
	}
	live := make(map[string]struct{}, len(liveCatalogIDs))
	for _, id := range liveCatalogIDs {
		live[id] = struct{}{}
	}
	for _, value := range report.Skipped {
		if _, ok := live[value]; ok {
			out = append(out, "skipped "+value+" (context unknown)")
		}
	}
	return out
}

func catalogSource(path string) string {
	raw, err := os.ReadFile(path)
	if err != nil {
		return path
	}
	var doc struct {
		Source string `yaml:"source"`
	}
	if yaml.Unmarshal(raw, &doc) == nil && strings.TrimSpace(doc.Source) != "" {
		return doc.Source
	}
	return path
}

func rejectOutputCollisions(protectedInputs, outputs []string) error {
	seen := make(map[string]struct{}, len(outputs))
	for _, output := range outputs {
		resolved, err := filepath.Abs(output)
		if err != nil {
			return err
		}
		key := strings.ToLower(filepath.Clean(resolved))
		if _, ok := seen[key]; ok {
			return fmt.Errorf("refusing duplicate output path %s", output)
		}
		seen[key] = struct{}{}
		for _, input := range protectedInputs {
			activeResolved, err := filepath.Abs(input)
			if err != nil {
				return err
			}
			if key == strings.ToLower(filepath.Clean(activeResolved)) {
				return fmt.Errorf("refusing to overwrite review input %s; choose a distinct generated/proposal output", input)
			}
		}
	}
	return nil
}

func ensureParent(path string) error {
	parent := filepath.Dir(path)
	if parent == "." || parent == "" {
		return nil
	}
	return os.MkdirAll(parent, 0o755)
}

func writeProposal(path string, body []byte) error {
	if err := ensureParent(path); err != nil {
		return err
	}
	return os.WriteFile(path, body, 0o644)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "catalog-review:", err)
	os.Exit(1)
}
